const appState = { profile: null, jobs: [], selectedJob: null };
const profileForm = document.querySelector('#profile-form');
const jobsNode = document.querySelector('#jobs');
const selectedJobNode = document.querySelector('#selected-job');
const generateButton = document.querySelector('#generate');
const documentsNode = document.querySelector('#documents');
const statusNode = document.querySelector('#status');
const toastNode = document.querySelector('#toast');

function toast(message) { toastNode.textContent = message; toastNode.classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => toastNode.classList.remove('visible'), 3800); }
async function request(url, options = {}) { const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'The local app could not complete that action.'); return body; }
function fillProfile(profile) { appState.profile = profile; for (const field of ['name','email','phone','headline','source_excerpt']) profileForm.elements[field].value = profile[field] || ''; profileForm.elements.skills.value = (profile.skills || []).join(', '); document.querySelector('#upload-note').textContent = profile.uploaded_file ? `Read locally from ${profile.uploaded_file}. Review every field before generating.` : 'Nothing has been uploaded yet.'; }
function renderJobs() { if (!appState.jobs.length) { jobsNode.innerHTML = '<p class="quiet">Save a candidate record to score the sample roles.</p>'; return; } jobsNode.innerHTML = appState.jobs.map(job => `<button class="job ${appState.selectedJob?.id === job.id ? 'selected' : ''}" data-job="${job.id}"><span class="score">${job.score}%</span><span><span class="job-title">${job.title}</span><span class="job-meta">${job.company} · ${job.location} · ${job.posted}</span></span><span class="match-count">${job.matches.length} signals</span></button>`).join('') + `<p class="match-note">Scores use only the saved candidate record and each listing's stated keywords. They are prompts for review—not a hiring prediction.</p>`; document.querySelectorAll('[data-job]').forEach(node => node.addEventListener('click', () => { appState.selectedJob = appState.jobs.find(job => job.id === node.dataset.job); selectedJobNode.textContent = appState.selectedJob.company; generateButton.disabled = false; renderJobs(); })); }
async function loadJobs() { const data = await request('/api/jobs'); appState.jobs = data.jobs; renderJobs(); }
async function saveProfile(event) { event?.preventDefault(); const form = new FormData(profileForm); const profile = { ...(appState.profile || {}), ...Object.fromEntries(form.entries()) }; const result = await request('/api/profile', { method: 'POST', body: JSON.stringify(profile) }); fillProfile(result.profile); await loadJobs(); toast(result.message); }
async function uploadCV(event) { const file = event.target.files[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) return toast('Choose a CV smaller than 8 MB.'); document.querySelector('#upload-note').textContent = `Reading ${file.name} locally…`; const raw = await file.arrayBuffer(); const bytes = new Uint8Array(raw); let binary = ''; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); try { const result = await request('/api/upload', { method: 'POST', body: JSON.stringify({ name: file.name, content: btoa(binary) }) }); fillProfile(result.profile); await loadJobs(); toast(result.message); } catch (error) { document.querySelector('#upload-note').textContent = error.message; toast(error.message); } }
async function generate() { if (!appState.selectedJob) return; generateButton.disabled = true; generateButton.textContent = 'Generating locally…'; try { const result = await request('/api/generate', { method: 'POST', body: JSON.stringify({ job_id: appState.selectedJob.id }) }); documentsNode.innerHTML = `<div class="document-summary">${result.message} Review the Typst source and PDFs before using them.</div>${result.errors?.length ? `<ul class="document-errors">${result.errors.map(error => `<li>${error}</li>`).join('')}</ul>` : ''}<div class="download-list">${result.files.map(file => `<a class="download" href="${file.url}"><span>Download</span>${file.name}</a>`).join('')}</div>`; toast(result.message); } catch (error) { toast(error.message); } finally { generateButton.disabled = false; generateButton.textContent = 'Generate CV and cover letter'; } }
async function initialize() { try { const [status, profile] = await Promise.all([request('/api/status'), request('/api/profile')]); statusNode.textContent = status.typst_available ? 'Typst is ready locally. Generated PDFs never leave this computer.' : 'Typst is not installed. The app will still generate downloadable .typ source files.'; fillProfile(profile); if (profile.name || profile.skills?.length || profile.source_excerpt) await loadJobs(); } catch (error) { statusNode.textContent = error.message; } }
document.querySelector('#cv-file').addEventListener('change', uploadCV); profileForm.addEventListener('submit', saveProfile); generateButton.addEventListener('click', generate); initialize();
