// ats-plain adapter — generated by typst-cv-studio. Deliberately NOT a reproduction:
// single column, conventional headings, no tables, no images, hyphenation off, so a
// parser reads every keyword. This is the build to submit through an application portal.
#import "../cv-content.typ": cv
#set text(hyphenate: false, font: "Liberation Serif", size: 10pt)
#set page(paper: "a4", margin: (x: 1.6cm, y: 1.4cm))
#set par(justify: false, leading: 0.62em)
#show heading.where(level: 2): it => block(breakable: false, above: 7pt, below: 3pt)[
  #text(size: 11pt, weight: "bold", fill: black)[#upper(it.body)]
]
#let sec(t) = [#heading(level: 2)[#t]]

#let style = cv.at("style", default: (:))
#let heading = style.at("heading", default: "profession")
#let doc-title = cv.at("doc-title", default: "")
#align(left)[
  #text(size: 15pt, weight: "bold")[#cv.author] \
  #if heading == "none" {} else if heading == "cv-label" { doc-title } else if heading == "profession+cv-label" { cv.profession + " · " + doc-title } else { cv.profession } \
  #cv.location \
  #cv.contact
]
#if cv.at("meta", default: none) != none { cv.meta }

#for s in cv.sections {
  sec(s.title)
  if s.at("prose", default: none) != none { s.prose }
  for e in s.at("entries", default: ()) {
    let line = (
      e.at("title", default: "")
      + (if e.at("subtitle", default: "") != "" { " — " + e.at("subtitle") } else { "" })
      + (if e.at("dates", default: "") != "" { " (" + e.at("dates") + ")" } else { "" })
    )
    if line != "" { [#line] }
    if e.at("location", default: "") != "" { [#e.at("location", default: "")] }
    for l in e.at("lines", default: ()) { [#l] }
    for b in e.at("bullets", default: ()) { list.item(b) }
  }
}
