// crest adapter — generated by typst-cv-studio.
// Settings copied from crest-cv's own template/main.typ: font "EB Garamond", 10pt,
// margin 2cm, accent #3a5a63, muted #5a5a55. This design is headerless by
// intent — contact details go on the show rule and there is no headline block — so no
// profession line is invented here. The `entry` helper below is the template's own.
#import "../cv-content.typ": cv
#import "../vendor/crest-cv/src/lib.typ": *
#let style = cv.at("style", default: (:))
#let accent = style.at("accent", default: "#3a5a63")
#let muted = rgb("#5a5a55")
#if style.at("hyphenate", default: none) != none { set text(hyphenate: style.hyphenate) }

#let entry(role: "", org: "", location: "", dates: "") = grid(
  columns: (1fr, auto),
  align: (left + top, right + top),
  column-gutter: 1em,
  [#strong[#role] #linebreak() #text(fill: muted)[#org]],
  [#text(fill: muted)[#dates] #linebreak() #text(fill: muted)[#location]],
)

#let heading = style.at("heading", default: "none")
#let doc-title = cv.at("doc-title", default: "")
#let sub = if heading == "none" { "" }   else if heading == "cv-label" { doc-title }   else if heading == "profession+cv-label" { cv.profession + (if doc-title != "" { " · " + doc-title } else { "" }) }   else if heading == "tagline" { cv.at("tagline", default: cv.profession) }   else { cv.profession }

#show: resume.with(
  author: cv.author,
  location: cv.location,
  email: cv.email,
  phone: cv.phone,
  social-links: cv.social,
  accent-color: accent,
  font: style.at("font", default: "EB Garamond"),
  font-size: style.at("size", default: 10pt),
  paper: "a4",
  margin: style.at("margin", default: 2cm),
)
#if sub != "" { align(center)[#text(fill: muted)[#sub]] }
#if cv.at("meta", default: none) != none { cv.meta }

#for s in cv.sections {
  cv-section(s.title, accent-color: accent)
  if s.at("prose", default: none) != none { s.prose }
  for e in s.at("entries", default: ()) {
    entry(
      role: e.at("title", default: ""),
      org: e.at("subtitle", default: ""),
      location: e.at("location", default: ""),
      dates: e.at("dates", default: ""),
    )
    for l in e.at("lines", default: ()) { [#l \ ] }
    for b in e.at("bullets", default: ()) { [- #b] }
  }
}
