// ridgeline adapter — generated by typst-cv-studio.
// Settings copied from ridgeline-cv's own template/main.typ: font "Raleway", 10pt,
// margin 1.4cm, accent #2b4c7e, and the design's own two-column cv-layout
// (wide main column + narrow meta rail). Sections named in the content module's
// `rail:` list go in the rail; everything else goes in main.
#import "../cv-content.typ": cv
#import "../vendor/ridgeline-cv/src/lib.typ": *
#let style = cv.at("style", default: (:))
#let accent = style.at("accent", default: "#2b4c7e")
#let rail-names = cv.at("rail", default: ("Core Competencies", "Language Proficiency", "Certifications"))
#if style.at("hyphenate", default: none) != none { set text(hyphenate: style.hyphenate) }

#show: resume.with(
  author: cv.author,
  font: style.at("font", default: "Raleway"),
  font-size: style.at("size", default: 10pt),
  paper: "a4",
  margin: style.at("margin", default: 1.4cm),
)

#let heading = style.at("heading", default: "profession")
#let doc-title = cv.at("doc-title", default: "")
#let sub = if heading == "none" { "" }   else if heading == "cv-label" { doc-title }   else if heading == "profession+cv-label" { cv.profession + (if doc-title != "" { " · " + doc-title } else { "" }) }   else if heading == "tagline" { cv.at("tagline", default: cv.profession) }   else { cv.profession }
#masthead(author: cv.author, profession: sub, accent-color: accent)

#cv-layout(
  accent-color: accent,
  main: [
    #for s in cv.sections [
      #if s.title not in rail-names [
        #cv-section(s.title, accent-color: accent)
        #if s.at("prose", default: none) != none { s.prose }
        #for e in s.at("entries", default: ()) {
          ridgeline-entry(
            title: e.at("title", default: ""),
            subtitle: e.at("subtitle", default: ""),
            dates: e.at("dates", default: ""),
            location: e.at("location", default: ""),
          )[
            #for l in e.at("lines", default: ()) { [#l \ ] }
            #for b in e.at("bullets", default: ()) { [- #b] }
          ]
        }
      ]
    ]
    #if cv.at("meta", default: none) != none { cv.meta }
  ],
  rail: [
    #let items = cv.at("contact-items", default: none)
    #if items != none { rail-contact(items, accent-color: accent) }
    #for s in cv.sections [
      #if s.title in rail-names [
        #cv-section(s.title, accent-color: accent)
        #if s.at("prose", default: none) != none { s.prose }
        #for e in s.at("entries", default: ()) [
          #if e.at("title", default: "") != "" and e.at("dates", default: "") != "" [
            #ridgeline-cred(name: e.title, issuer: e.at("subtitle", default: ""), date: e.at("dates", default: ""))
          ] else [
            #if e.at("title", default: "") != "" { [#strong[#e.at("title")] #linebreak()] }
            #for l in e.at("lines", default: ()) { [#l \ ] }
            #for b in e.at("bullets", default: ()) { [#b \ ] }
          ]
        ]
      ]
    ]
  ],
)
