// soft-and-hard adapter — generated by typst-cv-studio.
// This package has no template/main.typ preset to copy; it is driven by its own
// `styling` show rule, which is used unmodified here.
#import "../cv-content.typ": cv
#import "@preview/cv-soft-and-hard:0.1.0": styling, section, entry
#let style = cv.at("style", default: (:))
#let heading = style.at("heading", default: "profession")
#let doc-title = cv.at("doc-title", default: "")
#let sub = if heading == "none" { "" }   else if heading == "cv-label" { doc-title }   else if heading == "profession+cv-label" { cv.profession + (if doc-title != "" { " · " + doc-title } else { "" }) }   else if heading == "tagline" { cv.at("tagline", default: cv.profession) }   else { cv.profession }
#if style.at("hyphenate", default: none) != none { set text(hyphenate: style.hyphenate) }
#show: styling

#align(center)[
  = #cv.author \
  #sub \
  #cv.contact#h(0.6em) | #h(0.6em) #cv.location
]
#if cv.at("meta", default: none) != none { align(center)[#cv.meta] }

#for s in cv.sections {
  section(s.title)
  if s.at("prose", default: none) != none { s.prose }
  for e in s.at("entries", default: ()) {
    entry(
      [
        #if e.at("title", default: "") != "" { [*#e.at("title")*] }
        #if e.at("subtitle", default: "") != "" { [ _(#e.at("subtitle"))_] }
        #linebreak()
        #for l in e.at("lines", default: ()) { [#l \ ] }
        #for b in e.at("bullets", default: ()) { [- #b] }
      ],
      [#text(size: 9pt)[#e.at("dates", default: "")
        #if e.at("location", default: "") != "" [#h(0.6em)· #e.at("location")]]],
    )
  }
}
