// vertex adapter — generated by typst-cv-studio.
// Settings below are copied from vertex-cv's own template/main.typ: font "EB Garamond",
// 11pt, margin 1.5cm, accent #5c3a5f.
// Only the optional `style:` dict in cv-content.typ changes them.
#import "../cv-content.typ": cv
#import "../vendor/vertex-cv/src/lib.typ": *
#let style = cv.at("style", default: (:))
#let accent = style.at("accent", default: "#5c3a5f")
#let heading = style.at("heading", default: "profession")
#let doc-title = cv.at("doc-title", default: "")
#let sub = if heading == "none" { "" }   else if heading == "cv-label" { doc-title }   else if heading == "profession+cv-label" { cv.profession + (if doc-title != "" { " · " + doc-title } else { "" }) }   else if heading == "tagline" { cv.at("tagline", default: cv.profession) }   else { cv.profession }
#if style.at("hyphenate", default: none) != none { set text(hyphenate: style.hyphenate) }

#show: resume.with(
  author: cv.author,
  font: style.at("font", default: "EB Garamond"),
  font-size: style.at("size", default: 11pt),
  paper: "a4",
  margin: style.at("margin", default: 1.5cm),
)

#masthead(
  author: cv.author,
  profession: sub,
  accent-color: accent,
  contact: [#cv.contact #h(0.6em) | #h(0.6em) #cv.location],
)
#if cv.at("meta", default: none) != none { cv.meta }

#for s in cv.sections {
  cv-section(s.title, accent-color: accent)
  if s.at("prose", default: none) != none { s.prose }
  for e in s.at("entries", default: ()) {
    vertex-entry(
      title: e.at("title", default: ""),
      subtitle: e.at("subtitle", default: ""),
      dates: e.at("dates", default: ""),
      location: e.at("location", default: ""),
      meta: e.at("meta", default: ""),
    )[
      #for l in e.at("lines", default: ()) { [#l \ ] }
      #for b in e.at("bullets", default: ()) { [- #b] }
    ]
  }
}
